In [1]:
import anndata as ad
import torch 
import numpy as np

In [4]:
# shape = (69570, 19018)
base = ad.read_h5ad("../1gene-norman.h5ad")
base.obs

# base.obs['control'] = (base.obs['perturbation_name'] == 'control')
# base.obs
# sampled_columns = np.random.choice(len(base.obs.columns), 3, replace=False)
# print(sampled_columns)
# base = base[:, sampled_columns]
# base.var


guide_identity  read_count  \
index                                                                    
AAACCTGAGAAGAAGC-1    NegCtrl0_NegCtrl0__NegCtrl0_NegCtrl0        1252   
AAACCTGAGGCATGTG-1      TSC22D1_NegCtrl0__TSC22D1_NegCtrl0        2151   
AAACCTGCACGAAGCA-1  NegCtrl10_NegCtrl0__NegCtrl10_NegCtrl0         958   
AAACCTGCAGCCTTGG-1          MAML2_NegCtrl0__MAML2_NegCtrl0        1525   
AAACCTGCATCTCCCA-1          NegCtrl0_CEBPE__NegCtrl0_CEBPE         499   
...                                                    ...         ...   
TTTGTCAGTCAGAATA-8  NegCtrl11_NegCtrl0__NegCtrl11_NegCtrl0         914   
TTTGTCATCAGTACGT-8          FOXA3_NegCtrl0__FOXA3_NegCtrl0        2068   
TTTGTCATCCACTCCA-8          CELF2_NegCtrl0__CELF2_NegCtrl0         829   
TTTGTCATCCCAACGG-8        BCORL1_NegCtrl0__BCORL1_NegCtrl0         136   
TTTGTCATCTGGCGAC-8        MAP4K3_NegCtrl0__MAP4K3_NegCtrl0        1226   

                    UMI_count   coverage  gemgroup  good_coverage  \
index                                                               
AAACCTGAGAAGAAGC-1         67  18.686567         1           True   
AAACCTGAGGCATGTG-1        104  20.682692         1           True   
AAACCTGCACGAAGCA-1         39  24.564103         1           True   
AAACCTGCAGCCTTGG-1         66  23.106061         1           True   
AAACCTGCATCTCCCA-1         30  16.633333         1           True   
...                       ...        ...       ...            ...   
TTTGTCAGTCAGAATA-8         50  18.280000         8           True   
TTTGTCATCAGTACGT-8         95  21.768421         8           True   
TTTGTCATCCACTCCA-8         33  25.121212         8           True   
TTTGTCATCCCAACGG-8          9  15.111111         8           True   
TTTGTCATCTGGCGAC-8         59  20.779661         8           True   

                    number_of_cells  guide_AHR  guide_ARID1A  guide_ARRDC3  \
index                                                                        
AAACCTGAGAAGAAGC-1                2          0             0             0   
AAACCTGAGGCATGTG-1                1          0             0             0   
AAACCTGCACGAAGCA-1                1          0             0             0   
AAACCTGCAGCCTTGG-1                1          0             0             0   
AAACCTGCATCTCCCA-1                1          0             0             0   
...                             ...        ...           ...           ...   
TTTGTCAGTCAGAATA-8                1          0             0             0   
TTTGTCATCAGTACGT-8                1          0             0             0   
TTTGTCATCCACTCCA-8                1          0             0             0   
TTTGTCATCCCAACGG-8                1          0             0             0   
TTTGTCATCTGGCGAC-8                1          0             0             0   

                    ...  n_genes  n_genes_by_counts  total_counts  \
index               ...                                             
AAACCTGAGAAGAAGC-1  ...     4108               4108       19413.0   
AAACCTGAGGCATGTG-1  ...     3142               3142       13474.0   
AAACCTGCACGAAGCA-1  ...     2114               2114        6842.0   
AAACCTGCAGCCTTGG-1  ...     3783               3783       18869.0   
AAACCTGCATCTCCCA-1  ...     2854               2854       10707.0   
...                 ...      ...                ...           ...   
TTTGTCAGTCAGAATA-8  ...     3070               3070       13251.0   
TTTGTCATCAGTACGT-8  ...     3305               3305       14727.0   
TTTGTCATCCACTCCA-8  ...     2842               2842        9750.0   
TTTGTCATCCCAACGG-8  ...     2824               2824        8670.0   
TTTGTCATCTGGCGAC-8  ...     3058               3058       12514.0   

                    total_counts_mt  pct_counts_mt  leiden  perturbation_name  \
index                                                                           
AAACCTGAGAAGAAGC-1           1327.0       6.835625      10            control   
AAACCTGAGGCATGTG-1         

In [2]:
adata = ad.read_h5ad("./datasets/L008_prepped.h5ad")
adata.obs


target_gene    donor crispr cell_type  n_counts  n_genes   mt_frac  \
0           ZNF331  Donor#2  Cas9+     IFNg+    4055.0     1881  0.123551   
1           MAPK11  Donor#2  Cas9+     IFNg+    1997.0     1073  0.019529   
2             OAS3  Donor#2  Cas9+     IFNg+   11044.0     3155  0.045817   
3             IL7R  Donor#2  Cas9+     IFNg+   38119.0     6660  0.040295   
4             SOX4  Donor#2  Cas9+     IFNg+    2585.0     1561  0.042553   
...            ...      ...    ...       ...       ...      ...       ...   
316126         TOX  Donor#3  Cas9+    restim   19578.0     4508  0.069670   
316127      SLC2A3  Donor#3  Cas9+    restim    3733.0     1689  0.091347   
316128        BTG2  Donor#3  Cas9+    restim   32049.0     5401  0.074043   
316131         NTC  Donor#3  Cas9+    restim   30929.0     5601  0.070258   
316132       IL2RA  Donor#3  Cas9+    restim    4731.0     2056  0.039104   

        control  dose  split cov_name  cov_pert_name  
0             0   1.0   test    IFNg+   IFNg+_ZNF331  
1             0   1.0  train    IFNg+   IFNg+_MAPK11  
2             0   1.0  train    IFNg+     IFNg+_OAS3  
3             0   1.0  train    IFNg+     IFNg+_IL7R  
4             0   1.0   test    IFNg+     IFNg+_SOX4  
...         ...   ...    ...      ...            ...  
316126        0   1.0   test   restim     restim_TOX  
316127        0   1.0    ood   restim  restim_SLC2A3  
316128        0   1.0  train   restim    restim_BTG2  
316131        0   1.0  train   restim     restim_NTC  
316132        0   1.0  train   restim   restim_IL2RA  

[139564 rows x 12 columns]

In [22]:
grn = torch.load("./graphs/L008_grn_128.pth")
print(grn.x)

tensor([[ 1.8414e-03,  1.4067e-04, -3.1975e-03,  ..., -2.3051e-04,
         -5.0577e-04,  2.1707e-03],
        [ 2.3336e-04,  1.6187e-03, -3.3282e-03,  ..., -1.7175e-04,
         -2.2398e-03, -1.0595e-03],
        [-9.5302e-05,  3.5073e-03, -3.5602e-03,  ...,  1.9751e-04,
          4.4050e-05, -2.5409e-03],
        ...,
        [-5.7198e-04,  2.7968e-03,  2.3216e-03,  ...,  1.8880e-03,
          1.6176e-03,  3.2919e-03],
        [ 2.3753e-03, -2.4716e-03,  1.5561e-03,  ...,  1.0119e-03,
          1.7264e-03,  2.5486e-03],
        [-3.6970e-04,  4.0051e-04, -3.4064e-03,  ...,  1.6208e-03,
          1.6558e-03, -3.9020e-03]])


In [46]:
import torch

def generate_random_adjacency_matrix(n):
    # Create a random upper triangular matrix
    upper_tri = torch.triu(torch.randint(0, 2, (n, n)), diagonal=1)
    # Mirror the upper triangular matrix to the lower triangular part
    adjacency_matrix = upper_tri + upper_tri.T
    return adjacency_matrix

def adjacency_matrix_to_sparse(adjacency_matrix):
    # Find the indices of the edges
    edge_indices = adjacency_matrix.nonzero(as_tuple=False).t()
    return edge_indices

# Number of nodes
n = 5
adjacency_matrix = generate_random_adjacency_matrix(n)
sparse_edges = adjacency_matrix_to_sparse(adjacency_matrix)

print("Adjacency Matrix:")
print(adjacency_matrix)
print("\nSparse Edges:")
print(sparse_edges)

Adjacency Matrix:
tensor([[0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [1, 1, 0, 1, 1],
        [0, 0, 1, 0, 1],
        [0, 0, 1, 1, 0]])

Sparse Edges:
tensor([[0, 1, 2, 2, 2, 2, 3, 3, 4, 4],
        [2, 2, 0, 1, 3, 4, 2, 4, 2, 3]])
