In [2]:
import anndata as ad
import torch 
import numpy as np

In [7]:
# shape = (69570, 19018)
base = ad.read_h5ad("../1gene-norman.h5ad")
base.X.shape

# sampled_columns = np.random.choice(len(base.obs.columns), 3, replace=False)
# print(sampled_columns)
# base = base[:, sampled_columns]
# base.var


(69570, 19018)

In [41]:
adata = ad.read_h5ad("./datasets/L008_prepped.h5ad")
adata.uns['fields']


{'control': 'control',
 'covariates': array(['cell_type'], dtype=object),
 'dose': 'dose',
 'perturbation': 'target_gene',
 'split': 'split'}

In [22]:
grn = torch.load("./graphs/L008_grn_128.pth")
print(grn.x)

tensor([[ 1.8414e-03,  1.4067e-04, -3.1975e-03,  ..., -2.3051e-04,
         -5.0577e-04,  2.1707e-03],
        [ 2.3336e-04,  1.6187e-03, -3.3282e-03,  ..., -1.7175e-04,
         -2.2398e-03, -1.0595e-03],
        [-9.5302e-05,  3.5073e-03, -3.5602e-03,  ...,  1.9751e-04,
          4.4050e-05, -2.5409e-03],
        ...,
        [-5.7198e-04,  2.7968e-03,  2.3216e-03,  ...,  1.8880e-03,
          1.6176e-03,  3.2919e-03],
        [ 2.3753e-03, -2.4716e-03,  1.5561e-03,  ...,  1.0119e-03,
          1.7264e-03,  2.5486e-03],
        [-3.6970e-04,  4.0051e-04, -3.4064e-03,  ...,  1.6208e-03,
          1.6558e-03, -3.9020e-03]])


In [46]:
import torch

def generate_random_adjacency_matrix(n):
    # Create a random upper triangular matrix
    upper_tri = torch.triu(torch.randint(0, 2, (n, n)), diagonal=1)
    # Mirror the upper triangular matrix to the lower triangular part
    adjacency_matrix = upper_tri + upper_tri.T
    return adjacency_matrix

def adjacency_matrix_to_sparse(adjacency_matrix):
    # Find the indices of the edges
    edge_indices = adjacency_matrix.nonzero(as_tuple=False).t()
    return edge_indices

# Number of nodes
n = 5
adjacency_matrix = generate_random_adjacency_matrix(n)
sparse_edges = adjacency_matrix_to_sparse(adjacency_matrix)

print("Adjacency Matrix:")
print(adjacency_matrix)
print("\nSparse Edges:")
print(sparse_edges)

Adjacency Matrix:
tensor([[0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [1, 1, 0, 1, 1],
        [0, 0, 1, 0, 1],
        [0, 0, 1, 1, 0]])

Sparse Edges:
tensor([[0, 1, 2, 2, 2, 2, 3, 3, 4, 4],
        [2, 2, 0, 1, 3, 4, 2, 4, 2, 3]])
